name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Authenticate Docker with ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 113231054232.dkr.ecr.us-east-1.amazonaws.com

    - name: Build, Tag, and Push Image to ECR
      run: |
        docker build --no-cache -t xrayserver .
        docker tag xrayserver:latest 113231054232.dkr.ecr.us-east-1.amazonaws.com/xrayserver:latest
        docker push 113231054232.dkr.ecr.us-east-1.amazonaws.com/xrayserver:latest

    - name: Verify Image in ECR
      run: |
        aws ecr describe-images --repository-name xrayserver --query "imageDetails[?imageTag=='latest'].[imageDigest]" --output text

    - name: Deploy to EC2 via SSM
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
          --parameters 'commands=[
            "docker stop streamlit-container || true",
            "docker rm streamlit-container || true",
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 113231054232.dkr.ecr.us-east-1.amazonaws.com",
            "docker pull 113231054232.dkr.ecr.us-east-1.amazonaws.com/xrayserver:latest",
            "docker images",
            "docker run -d --name streamlit-container -p 8501:8501 113231054232.dkr.ecr.us-east-1.amazonaws.com/xrayserver:latest"
          ]' \
          --timeout-seconds 600
